basePath: /
definitions:
  user.loginAddressParam:
    properties:
      address:
        type: string
      message:
        type: string
      signature:
        type: string
    required:
    - address
    - message
    - signature
    type: object
  user.loginParam:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  user.registerParam:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
  description: 通用管理后台
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BasicAdmin
  version: "1.0"
paths:
  /api/v1/account/add:
    post:
      consumes:
      - application/json
      description: 创建账户
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 创建账户
      tags:
      - 账户管理
  /api/v1/account/del:
    post:
      consumes:
      - application/json
      description: 删除账户
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 删除账户
      tags:
      - 账户管理
  /api/v1/account/detail:
    get:
      consumes:
      - application/json
      description: 获取账户详情
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 获取账户详情
      tags:
      - 账户管理
  /api/v1/account/edit:
    post:
      consumes:
      - application/json
      description: 编辑账户
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 编辑账户
      tags:
      - 账户管理
  /api/v1/account/list:
    get:
      consumes:
      - application/json
      description: 获取账户列表
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 获取账户列表
      tags:
      - 账户管理
  /api/v1/role/add:
    post:
      consumes:
      - application/json
      description: 创建角色
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 创建角色
      tags:
      - 角色管理
  /api/v1/role/del:
    post:
      consumes:
      - application/json
      description: 删除角色
      parameters:
      - description: 删除id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 删除角色
      tags:
      - 角色管理
  /api/v1/role/detail:
    get:
      consumes:
      - application/json
      description: 查看角色详情
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 查看角色详情
      tags:
      - 角色管理
  /api/v1/role/edit:
    post:
      consumes:
      - application/json
      description: 编辑角色
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 编辑角色
      tags:
      - 角色管理
  /api/v1/role/list:
    get:
      consumes:
      - application/json
      description: 查看角色列表
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 查看角色列表
      tags:
      - 角色管理
  /api/v1/sys-api/del:
    post:
      consumes:
      - application/json
      description: 删除api接口
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 删除api接口
      tags:
      - 接口管理
  /api/v1/sys-api/edit:
    post:
      consumes:
      - application/json
      description: 更新api接口
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 更新api接口
      tags:
      - 接口管理
  /api/v1/sys-api/list:
    get:
      consumes:
      - application/json
      description: api接口列表
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: api接口列表
      tags:
      - 接口管理
  /api/v1/sys-opera-log/del:
    post:
      consumes:
      - application/json
      description: 删除操作记录
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 删除操作记录
      tags:
      - 操作日志
  /api/v1/sys-opera-log/detail:
    get:
      consumes:
      - application/json
      description: 操作记录详情
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 操作记录详情
      tags:
      - 操作日志
  /api/v1/sys-opera-log/list:
    get:
      consumes:
      - application/json
      description: 操作记录列表
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
      summary: 操作记录列表
      tags:
      - 操作日志
  /api/v1/user/detail:
    get:
      consumes:
      - application/json
      description: 获取用户的详情
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功获取用户的详情
          schema:
            type: string
      summary: 获取用户的详情
      tags:
      - 用户操作
  /api/v1/user/login/address:
    post:
      consumes:
      - application/json
      description: 钱包登录
      parameters:
      - description: login with param
        in: body
        name: loginParam
        required: true
        schema:
          $ref: '#/definitions/user.loginAddressParam'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: 钱包登录
      tags:
      - 用户操作
  /api/v1/user/login/username:
    post:
      consumes:
      - application/json
      description: 账密登录
      parameters:
      - description: login with param
        in: body
        name: loginParam
        required: true
        schema:
          $ref: '#/definitions/user.loginParam'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: 账密登录
      tags:
      - 用户操作
  /api/v1/user/logout:
    get:
      consumes:
      - application/json
      description: 用户登出
      produces:
      - application/json
      responses:
        "200":
          description: 用户登出成功
          schema:
            type: string
      summary: 用户登出
      tags:
      - 用户操作
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册参数
        in: body
        name: registerParam
        required: true
        schema:
          $ref: '#/definitions/user.registerParam'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            type: string
      summary: 用户注册
      tags:
      - 用户操作
  /api/v1/user/register/verify:
    get:
      consumes:
      - application/json
      description: 验证注册信息
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功，请进入登录页面
          schema:
            type: string
      summary: 验证注册信息
      tags:
      - 用户操作
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
